### ISSUE TITLE
820-3115

### ISSUE THREAD

**Issue by Aripurnom0** [MuertoGB/SMCTool#1]
Can for 820-3115?sir

**Comment by MuertoGB** [comment]
Currently, no, I have not found any compatible payloads for this board. I'll look into it.

**Comment by Aripurnom0** [comment]
Thankyo so much. but you are so awazing 🙏🏻

**Comment by MuertoGB** [comment]
Okay, I've found that single file payloads from boards like the 3115, 3332 cannot be flashed. It seems MacOS signs the payload on the fly and I'm unsure currently how the process fully works. No promises on time frame or whether it will actually happen., but I'm working on it.

**Comment by Aripurnom0** [comment]
ok sir your knowledge is amazing 🙏🏻🙏🏻

**Comment by MauricioJV92** [comment]
if you need any kind of BIOS backup let me know as I work with boards and may have boards available.  greetings from Chiapas, Mexico

**Comment by MuertoGB** [comment]
Thanks everyone, I'll close here now.

**Comment by Aripurnom0** [comment]
Thanks you sir 🙏🏻
