### ISSUE TITLE
Need compatibility with a new Model

### ISSUE THREAD

**Issue by camobert** [MuertoGB/SMCTool#10]
I need this Tool for my MacBook Pro 9,1 please.

Model: A1286
EMC: 2556
Board ID: Mac-4B7AC7E43945597E
Board Model: 820 – 3330
GPU:  NVIDIA GeForce GT 650M and Intel HD Graphics 4000

Thank You.

**Comment by MuertoGB** [comment]
SMCTool does not currently support pre-2013 models with single file payloads. I don't have a timeframe on compatibility.

Currently, to my knowledge, we need all four payloads. 2012 LM4F payloads only contain the single appcode payload. When replacing an SMC the base, update, appcode and EPM need flashing, where we only have access to the appcode.

**Comment by camobert** [comment]
Okay, thanks anyway.
Thanks for the quick reply.
I have to look for another way to reset the SMC, unfortunately the power button no longer works on the MacBook.

**Comment by MuertoGB** [comment]
If just the power button isn't working, you can manually short PM_PWRBTN_L to ground and see if the device boots. Next to R2585 there is a testpoint that can be shorted to C2580 PIN 2. If this works, replace the power button.

You can also achieve this by shorting SMC_ONOFF_L to ground, however this won't rule out an issue on PM_PWRBTN_L.
