### ISSUE TITLE
Usage issue

### ISSUE THREAD

**Issue by passmoregames** [MuertoGB/SMCTool#5]
I just want to clarify that I have used EFI Shell a lot, including while building many hackintoshes and editing BIOS settings. For whatever reason I cannot get SMCTool to properly load. I get the EFI block list, and then the usual 'press ESC in' dialog. I then wait until that passes and am met with Shell> without any of the SMCTool dialog that comes up in your video of it being used. 

I can then type a command like '820-3476.nsh' and it just gives me the error '820-3476.nsh is not recognized as an internal or external command'. 

It's like it is loading the EFI shell included within SMCTOOL, without actually loading smctool.

I have tried manually copying the files to the usb stick in macos and windows. I've tried flashing it using an iso flasher in macos, and also in Rufus. I have also tried exFAT, HFS+ and FAT. I am using a 64gb usb2 stick and it is formatted for GPT.

Any idea what's going wrong?

**Comment by passmoregames** [comment]
Just to add - I was able to get around this issue by mounting into the correct FS within EFI Shell (in my case it was FS7:) for the USB stick and then running 'startup.nsh' from there. Weird it's not working automatically.

**Comment by MuertoGB** [comment]
Could you do me something, format the memory stick using MBR and see if the issue is fixed?

**Comment by passmoregames** [comment]
Just tried that - I'm afraid not.

**Comment by MuertoGB** [comment]
Leave it with me, I'll see if I can dig up what could be causing it.

**Comment by passmoregames** [comment]
ok! Thank you.

**Comment by phamthai2503** [comment]
after showing ESC and not seeing SMCTool appear, you can type " FS1: " then type " ls" to see if it's your USB? if not been then " FS2: " after that type " ls" , keep running until you see the contents of your USB, then type startup.nsh

**Comment by MuertoGB** [comment]
> ok! Thank you.

Can you please tell the USB stick model you were using?

**Comment by MuertoGB** [comment]
> after showing ESC and not seeing SMCTool appear, you can type " FS1: " then type " ls" to see if it's your USB? if not been then " FS2: " after that type " ls" , keep running until you see the contents of your USB, then type startup.nsh

passmoregames already covered this here:
https://github.com/MuertoGB/SMCTool/issues/5#issuecomment-1280919593

**Comment by MuertoGB** [comment]
I will close here now due to inactivity. This issue can be resolved by removing the internal storage device.
