### ISSUE TITLE
SMC tool a1398

### ISSUE THREAD

**Issue by Shazz00** [MuertoGB/SMCTool#8]
![1FAE6453-0DA6-4A45-B54B-980A55D601D6](https://user-images.githubusercontent.com/123956125/215483535-a1aae504-7d73-4610-970d-3692437d98c5.jpeg)
Hallo , sir 
After programming 820-00138-A using smc tool smc power management problem shows.  A system that has no problems .

**Comment by MuertoGB** [comment]
This is not enough information to help you.

What was the initial issue that required you to flash the SMC? Also, is the board iGPU, or dGPU?

**Comment by MuertoGB** [comment]
@Shazz00 I've spotted a mistake in board-ids, a fix is incoming. Please bare with me.

**Comment by MuertoGB** [comment]
Download this test build and reflash your SMC with 820-00138.nsh. Simply drag all the files from the zip and overwrite anything on your SMCTool USB.

https://github.com/MuertoGB/SMCTool/archive/refs/heads/v106_fix.zip

Please report back.

**Comment by Shazz00** [comment]
![image](https://user-images.githubusercontent.com/123956125/215685965-d875d2fc-28fe-4fce-927c-4e42ba0453e2.jpeg)


Thank you sir,   ❤️

**Comment by MuertoGB** [comment]
Excellent news. Thanks for bringing this to my attention. I'll close here.
